version: '3.5'

services:
  kotlin-ecommerce:
    container_name: "kotlin-ecommerce"
    image: kotlin-ecommerce:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_PASSWORD: kotlin
      DATABASE_USER: kotlin
      DATABASE_URL: jdbc:postgresql://kotlin-restful-api-postgres:5432/restful-api-kotlin

  kotlin-restful-api-postgres:
    container_name: "kotlin-restful-api-postgres"
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: restful-api-kotlin